Create the-journal-of-the-indian-law-institute.csl
citation-style-language/styles pull request #5100
Opened 2020-11-13 11:38 UTC by POBrien333

via https://forums.zotero.org/discussion/84206/style-request-the-journal-of-the-indian-law-institute-annual-survey-of-indian-law#latest

2020-11-13 21:11 UTC, bwiernik requested changes

2020-11-13 21:11 UTC, bwiernik commented on the-journal-of-the-indian-law-institute.csl
> +  <macro name="contributors-short">
This macro isn't used anywher.

2020-11-13 21:11 UTC, bwiernik commented on the-journal-of-the-indian-law-institute.csl
> +  <macro name="title-short">
This macro isn't used anywhere.

2020-11-13 21:11 UTC, bwiernik commented on the-journal-of-the-indian-law-institute.csl
> +  <macro name="locators-subsequent">
Macro not used anywhere.

2020-11-15 05:30 UTC, merged

2020-11-15 05:30 UTC, rmzelle commented
@POBrien333, thanks!