Create sports-health.csl
citation-style-language/styles pull request #5620
Opened 2021-09-03 08:26 UTC by POBrien333

via https://forums.zotero.org/discussion/90674/sport-health#latest

Unsure about this one. Please review. :)

2021-09-05 01:58 UTC, adam3smith requested changes
A couple of suggestions/fixes

2021-09-05 01:58 UTC, adam3smith commented on sports-health.csl
> +  <bibliography hanging-indent="false" et-al-min="7" et-al-use-first="3" second-field-align="flush">
definitely needs to be sorted alphabetically

2021-09-05 01:58 UTC, adam3smith commented on sports-health.csl
> +          <if variable="DOI">
```suggestion
          <if variable="PMID">
```

2021-09-05 01:58 UTC, adam3smith commented on sports-health.csl
> +                    <text value="Published online"/>
I'd do [Epub ahead of print] here as per the style guidelines?

2021-09-06 03:14 UTC, rmzelle commented
Metadata looks fine.

2021-09-06 08:37 UTC, POBrien333 commented
Thanks for the thorough review. :)

2021-09-06 17:24 UTC, merged