Create anglia-ruskin-erhvervsakademi-aarhus.csl
citation-style-language/styles pull request #5633
Opened 2021-09-15 12:03 UTC by saphyron

edted anglia rusking syle for use in Erhvervsakademi Aarhus and Businessakademi Aarhus

2021-09-15 23:50 UTC, adam3smith requested changes
I left a couple of initial notes - I'll likely have more as we look more closely, but wanted to understand first what exactly the style is for:
- is there a published guide?
- in what languages would this be used and by whom?
- what's the relationship to Anglia Ruskin?

2021-09-15 23:50 UTC, adam3smith commented on anglia-ruskin-erhvervsakademi-aarhus.csl
> +  <locale xml:lang="en">
It looks like you copies all of APAs locales here? Was that on purpose? In which languages is this style effectively going to be used?

2021-09-15 23:50 UTC, adam3smith commented on anglia-ruskin-erhvervsakademi-aarhus.csl
> +      <else-if match="none" variable="author">
That's probably not right as it will mark edited volumes as Anon ( see the Hancke et al. in the preview)

2021-09-16 00:27 UTC, saphyron commented
> I left a couple of initial notes - I'll likely have more as we look more closely, but wanted to understand first what exactly the style is for:
> 
> * is there a published guide?
> * in what languages would this be used and by whom?
> * what's the relationship to Anglia Ruskin?

1) Yes and no. Will need to get hold of my teacher to get the documentation its based.
2) Danish & English will be the primary languages, but when I asked which languages to put in, she told me just to keep them all in case a language will be needed later.
2.1) It will be used by students from Erhvervsakademi Aarhus and Businessakademi Aarhus.
3) The initial template was by Anglia Ruskin, Anglia Ruskin had some errors in regards to how the teaching staff wanted it to be and the documentation, so I was told to work on fixing these errors and incorporate them into an edited style.

2021-09-19 01:32 UTC, adam3smith commented
OK, but that's just the guide for Anglia Ruskin, which we already implement. There's no published version -- or a version that you'd be able to share here -- of the guidelines for Erhvervsakademi Aarhus? We have a pretty firm rule against publishing styles for which we and others aren't able to verify accuracy ourselves, so we require a link to or upload of the relevant guidelines.

2021-09-19 04:01 UTC, saphyron commented
> OK, but that's just the guide for Anglia Ruskin, which we already implement. There's no published version -- or a version that you'd be able to share here -- of the guidelines for Erhvervsakademi Aarhus? We have a pretty firm rule against publishing styles for which we and others aren't able to verify accuracy ourselves, so we require a link to or upload of the relevant guidelines.

Thanks for the reply have sent this information further to my teacher. When I know more information I will reply below.

2021-09-20 13:37 UTC, saphyron commented
I have received a initial response back from my Teacher. I have tried to translate it to English as best as I can.

According to my teacher, the Anglia Ruskin style currently in Zotero right now, does not correspond to ARUH (Anglia Ruskin University Havard) documentation, which is the main reason I was asked to edit the style for use on Erhvervsakademi Aarhus. In addition, some of the errors found in the Style were hard to fix due to the limitations with Zotero item types.
Due to this the ARUH is the closest documentation to either styles. 

On that note we will be working on a simple documentation, for the "Anglia Ruskin - Erhvervsakademi Aarhus style".

2022-01-14 15:50 UTC, closed without merging