Create tyndale-bulletin-fullnote-bibliography
citation-style-language/styles pull request #5673
Opened 2021-10-20 18:12 UTC by dstark

Create style for the Tyndale Bulletin.

2021-10-20 20:33 UTC, dstark commented
@rmzelle The file I've submitted to create this new style passes CSL validation, but I'm obviously doing something wrong in the submission process as the checks don't all pass. But I'm not sure what I'm being told is wrong on the styles/locales front. Could I trouble you for some pointing in the right direction?

Thanks so much!

2021-10-29 21:20 UTC, dstark commented
> They just have that one style, right? In that case we'd go without nthe fullnote, bibliography in title and id Also, do they have an issn?

Yes. Just the one style, and I've submitted a revised file that includes the (e)issn information.

2021-10-30 00:45 UTC, adam3smith requested changes
Could you still rename as indicated? Rest looks great, thanks!

2021-10-30 00:45 UTC, adam3smith commented on tyndale-bulletin-fullnote-bibliography.csl
> +    <title>Tyndale Bulletin (full note, bibliography)</title>
Sorry, wasn't clear here: if there's just one style, this should just be `Tyndale Bulletin`

2021-10-30 00:45 UTC, adam3smith commented on tyndale-bulletin-fullnote-bibliography.csl
> +    <id>http://www.zotero.org/styles/tyndale-bulletin-fullnote-bibliography</id>
This should be 
```suggestion
    <id>http://www.zotero.org/styles/tyndale-bulletin</id>
```
etc. for filename, and self link

2021-11-01 00:43 UTC, merged

2021-11-01 00:43 UTC, adam3smith commented
Thanks!

2021-11-01 15:13 UTC, dstark commented
@adam3smith thanks for approving the style. My apologies I misread the earlier post as saying _if_ it was decided to drop the fullnote-bibliography terminology from the style name and such rather than that _was_ what was to be done. ;-)

Appreciate your help.