Update turabian-author-date.csl
citation-style-language/styles pull request #5695
Opened 2021-10-29 15:15 UTC by dstark

Corrects the citation output in three cases:

1) inclusion of seasons of publication in journal article reference list items,
2) in-text citations for reprinted books, and 
3) reference list items for reprinted books.

2021-10-31 12:58 UTC, adam3smith requested changes
Thanks! A couple of small requests

2021-11-01 14:58 UTC, dstark reviewed
Revised file with 3 requested changes from @adam3smith.

2021-11-01 15:36 UTC, adam3smith requested changes
One comment left to delete. Than!

2021-11-01 15:36 UTC, adam3smith commented on turabian-author-date.csl
> +    <!-- Omits the original publication date in the in-text citation per Turabian, 9th ed., §19.1.4. -->
This comment is no longer relevant/correct, please delete

2021-11-02 02:12 UTC, merged

2021-11-02 02:12 UTC, adam3smith commented
Thanks!