Create ABNT NBR 6023:2018. UNESP – Faculdade de Engenharia de Guarati…
citation-style-language/styles pull request #5705
Opened 2021-11-05 21:11 UTC by suelencfmorais

Hello ,
I request the inclusion of my Institution's style in the community repository.
Thank you.

2021-11-10 02:28 UTC, adam3smith commented
THe remaining errors are validation errors: https://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2F6ad148ab5a131a34bac32cca5029fec8f2809035%2Funiversidade-estadual-paulista-faculdade-de-engenharia-de-guaratingueta-abnt.csl&version=1.0.1
You'll need to fix them -- see above for how to update your pull request

2021-12-01 12:22 UTC, suelencfmorais commented
I realized that my Instituiton's style isn't available. What's the next step needed for the style availability in repository, which can be found in Zotero and Mendeley?

2021-12-04 01:32 UTC, adam3smith commented
I just noticed -- there's no link to documentation for the style -- are the guidelines available online somewhere? Where?

2021-12-06 22:57 UTC, suelencfmorais commented
Hello, we changed the style and put the address where the style is hosted. We would like to know if this will integrate the style into the international repository for zotero and mendeley.

2021-12-27 02:36 UTC, adam3smith requested changes

2021-12-27 02:36 UTC, adam3smith commented on universidade-estadual-paulista-faculdade-de-engenharia-de-guaratingueta-abnt.csl
> +    <title>Universidade Estadual Paulista - Faculdade de Engenharia de Guaratingueta- ABNT (Português - Brasil)</title>
```suggestion
    <title>Universidade Estadual Paulista - Faculdade de Engenharia de Guaratingueta - ABNT (Português - Brasil)</title>
```

2021-12-27 02:44 UTC, merged

2021-12-27 02:44 UTC, adam3smith commented
Sorry for the delay!

2022-02-03 21:04 UTC, suelencfmorais commented
Hello, I can't find in Mendeley the style that I submited, I just found in Zotero. Someone coul'd help with this? tks.

2022-02-03 21:34 UTC, adam3smith commented
That's a question for Mendeley; we have no insight into when/how they update styles.

2022-09-17 23:14 UTC, imsys commented
@suelencfmorais, I'm using Zotero and I found the style you created extremely helpful!

I'm just checking the [NBR 6023:2018 documentation](http://plone.ufpb.br/secretariado/contents/documentos/2020ABNT60232018VersoCorrigida.pdf) and it says it can show the ISBN and DOI just before the URLs, so I would suggest to add the following inside the "access" macro, or in your preferred way.

```xml
  <macro name="access">
    <text variable="ISBN" prefix="ISBN " suffix=". "/>
    <text variable="DOI" prefix="DOI " suffix=". "/>
    <choose>
```
I also would like to know if we could create a numbered version, like: ²³, we could use `nature.csl` as a basis for working on that.