Create gomis-senegalese-medicine-thesis.csl
citation-style-language/styles pull request #5774
Opened 2021-12-10 00:42 UTC by drgomis

Vancouver style with some changes in order to create the right style for thesis and dissertations from Senegalese medical universities. The main change is the display of the references in alphabetical order.

2021-12-11 21:21 UTC, drgomis commented
Vancouver style with some changes in order to create the right style for thesis and dissertations from Faculté de Médecine et d'Odontologie of Université Cheikh Anta Diop de Dakar. The main change is the display of the references in alphabetical order. We use the veterinary-pathololy.csl files to start this work.

2021-12-21 11:31 UTC, adam3smith requested changes

2021-12-21 11:31 UTC, adam3smith commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +    <title>Université Cheikh Anta Diop - Faculté de Médecine de Pharmacie et d'Odontologie</title>
```suggestion
    <title>Université Cheikh Anta Diop - Faculté de Médecine de Pharmacie et d'Odontologie (Français)</title>
```

2021-12-21 16:12 UTC, drgomis commented
Thank you @adam3smith.

2021-12-31 10:57 UTC, adam3smith reviewed
Some more questions

2021-12-31 23:21 UTC, drgomis commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +  </locale>
Hello @adam3smith,
What, I have to change in this section?

2021-12-31 23:34 UTC, drgomis commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +      <key variable="author"/>
Yes, it is the style of our faculty.

2021-12-31 23:50 UTC, drgomis commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +  <bibliography et-al-min="7" et-al-use-first="3" second-field-align="flush">
Thank you for this remark. It's et-al-use-first="6". I will change it.

2022-01-01 16:15 UTC, adam3smith commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +      <key variable="author"/>
I understand you want alphabetical sorting in the bibliography, but do you really want [3, 1] or even [2,5,1] in text. I find that hard to believe

2022-01-01 16:19 UTC, adam3smith commented
Your link to documentation doesn't actually go to documentation for the style - is that available somewhere? That would also help with answering the remaining question on sorting

2022-01-01 20:57 UTC, drgomis commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +      <key variable="author"/>
No, in the text I want to put it in [1, 3] or [1, 2, 5], and if the numbers follow each other in [5-10].

2022-01-01 21:05 UTC, drgomis commented
**> Your link to documentation doesn't actually go to documentation for the style - is that available somewhere? That would also help with answering the remaining question on sorting**

You can see, what I really want in these two documents in the attached files. The documentation isn't online yet because I just finished writing it.

[Modele automatisation des citations et references selon le fichier csl UCAD-FMPO. Gomis.pdf](https://github.com/citation-style-language/styles/files/7798237/Modele.automatisation.des.citations.et.references.selon.le.fichier.csl.UCAD-FMPO.Gomis.pdf)
[Proposition Guide de références bibliographiques theses memoires UCAD-FMPO. Gomis.pdf](https://github.com/citation-style-language/styles/files/7798238/Proposition.Guide.de.references.bibliographiques.theses.memoires.UCAD-FMPO.Gomis.pdf)

2022-01-01 21:33 UTC, drgomis commented on universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-et-dodontologie.csl
> +      <key variable="author"/>
I understand. I will change it right now to  "sorted in the text by citation-number".

2022-01-02 02:40 UTC, adam3smith commented
(don't worry about the test failures; they're not because of you)

2022-01-02 03:18 UTC, drgomis commented
Ok, I see. I think there is a problem with the csl validator.
So, thank you for the information.

2022-01-03 19:54 UTC, drgomis commented
@adam3smith, when can I try again for the style test?

2022-01-05 02:28 UTC, drgomis commented
Thank you @adam3smith.

2022-01-05 03:10 UTC, merged

2022-01-05 03:44 UTC, drgomis commented
Thank you @adam3smith. I want to know how long it will take for the style to be uploaded in the Zotero repository?

2022-01-05 11:21 UTC, adam3smith commented
Typically within an hour. It's available now

2022-01-05 17:32 UTC, drgomis commented
I see. Thank you again.