Patch 3
citation-style-language/styles pull request #5825
Opened 2022-01-04 14:09 UTC by simomac

adding missing publisher-place to book ref.

2022-01-04 14:15 UTC, adam3smith commented
(test failure is unrelated to your style)

2022-01-04 14:31 UTC, simomac commented
'(test failure is unrelated to your style)...' Hi, I'm fairly new to git can you advise what I need to do?

2022-01-04 14:36 UTC, adam3smith commented
Nothing for now -- we've updated our automated checks but the branch from which you made your pull request predated those changes, so they fail.

2022-01-04 15:46 UTC, bwiernik commented on harvard-imperial-college-london.csl
> +   <macro name="editor">
```suggestion
  <macro name="editor">
```

2022-01-04 15:48 UTC, bwiernik requested changes

2022-01-04 15:48 UTC, bwiernik commented on harvard-imperial-college-london.csl
> +          <text variable="publisher-place"/>
There is no delimiter between publisher and publisher-place here. You should put these inside a `<group delimiter=", ">`

2022-01-04 20:01 UTC, retorquere commented
The current test failure in this PR is not related to the re-indenter, the CSL-style-rendering phase reports errors. Other PRs that failed because of the re-indenter have been restarted and run green again.

2022-01-04 20:09 UTC, retorquere commented
Although we could make it so that if it's labeled safe to test Sheldon will allow mixed patches.

2022-01-05 13:29 UTC, merged

2022-01-05 13:29 UTC, adam3smith commented
Thanks!