Create effective-altruism-wiki.csl
citation-style-language/styles pull request #5829
Opened 2022-01-06 15:52 UTC by benthamite

Citation style for the [Effective Altruism Wiki](https://forum.effectivealtruism.org/tag/ea-wiki-faq).

2022-01-06 16:08 UTC, bwiernik commented
Thanks! Can you add a template link to the style you based this off of, and also a link to the documentation for the style?

2022-01-06 16:22 UTC, adam3smith commented
@retorquere -- sorry to trouble you one more time, but this shouldn't fail, I think. Looks like it's looking for Sheldon in the wrong path (3.0.0 instead of 3.0.2) -- is there a wrong ruby version somewhere?

2022-01-06 16:27 UTC, retorquere commented
No trouble. Something must have changed in the environment sheldon runs in, as it is just flaming out entirely. I'm looking into it.

2022-01-06 19:21 UTC, retorquere commented
OK, so sheldon works again, but this ties into the issue that it really is in need of retirement.

2022-01-06 20:10 UTC, bwiernik requested changes

2022-01-06 20:10 UTC, bwiernik commented on effective-altruism-wiki.csl
> +<style xmlns="http://purl.org/net/xbiblio/csl" class="note" version="1.0" and="symbol" delimiter-precedes-et-al="never" delimiter-precedes-last="never" et-al-min="4" et-al-use-first="1" initialize="t
Please run your style through https://formatter.citationstyles.org/ to fix the indenting

2022-01-06 20:10 UTC, bwiernik commented on effective-altruism-wiki.csl
> +      <term name="et-al"> /et al./</term>
Is ` /et al./` org mode syntax?

2022-01-06 20:12 UTC, bwiernik commented
Thanks! A few comments to start. This is based on APA 6 correct?

2022-01-06 22:04 UTC, benthamite commented
My sincere apologies: I now see that I submitted the wrong file. I have two csl files: a markdown version and an org-mode version. I intended to submit the former, which had been run through the formatter and had all the words fully spelled out, but I made a mistake and submitted the org-mode version instead. Should I create a new pull request?

I'm sorry, again, for wasting your time.

2022-01-06 22:33 UTC, adam3smith commented
You can just switch it out in this PR

Sent from my phone

On Thu, Jan 6, 2022, 17:04 Pablo Stafforini ***@***.***>
wrote:

> My sincere apologies: I now see that I submitted the wrong file. I have
> two csl files: a markdown version and an org-mode version. I intended to
> submit the former, which had been run through the formatter and had all the
> words fully spelled out, but I made a mistake and submitted the org-mode
> version instead. Should I create a new pull request?
>
> I'm sorry, again, for wasting your time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/citation-style-language/styles/pull/5829#issuecomment-1006967920>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA7PWQNG7G6TP3ZTBRJTLDUUYGX3ANCNFSM5LMUDLBQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-01-07 00:24 UTC, bwiernik commented
It's no time waste at all. We're just doing some basic review of the style

2022-01-07 01:42 UTC, adam3smith commented
No concerns from me. @bwiernik I'll let you merge once you're reviewed

2022-01-07 11:20 UTC, bwiernik requested changes
A few minor suggestions and corrections

2022-01-07 11:20 UTC, bwiernik commented on effective-altruism-wiki.csl
> +      </else-if>
```suggestion
```

2022-01-07 11:20 UTC, bwiernik commented on effective-altruism-wiki.csl
> +      <if type="article article-journal article-magazine article-newspaper review review-book" match="any">
```suggestion
      <if type="article-journal article-magazine article-newspaper review review-book" match="any">
```

2022-01-07 11:20 UTC, bwiernik commented on effective-altruism-wiki.csl
> +          <group delimiter=", " suffix=", ">
```suggestion
          <group delimiter=", " prefix=", ">
```

2022-01-07 12:02 UTC, merged

2022-01-07 12:02 UTC, bwiernik commented
Thanks!