Create physiotherapy-theory-and-practice.csl
citation-style-language/styles pull request #5833
Opened 2022-01-10 09:12 UTC by POBrien333

via https://forums.zotero.org/discussion/86539/physiotherapy-theory-and-practise#latest

2022-01-10 20:01 UTC, bwiernik requested changes

2022-01-10 20:01 UTC, bwiernik commented on physiotherapy-theory-and-practice.csl
> +            <text variable="title" suffix="."/>
Needs a space on the suffix here. Should probably be a group delimiter instead.

2022-01-10 20:01 UTC, bwiernik commented on physiotherapy-theory-and-practice.csl
> +            <text variable="title"/>
This needs a group delimiter between title and container information.

2022-01-10 20:01 UTC, bwiernik commented on physiotherapy-theory-and-practice.csl
> +            <text variable="title" suffix="."/>
Suffixes need spaces. Should be group delimiters instead.

2022-01-10 20:01 UTC, bwiernik commented on physiotherapy-theory-and-practice.csl
> +            <text variable="title"/>
Same as above. Group delimiters.

2022-01-11 08:38 UTC, POBrien333 commented
No idea what happened, but just reworked this. Loads of errors in it. Must've gotten distracted and then thought it was finished without thinking about it.

2022-01-12 15:24 UTC, merged

2022-01-12 15:24 UTC, bwiernik commented
Thanks!