Update harvard-anglia-ruskin-university.csl
citation-style-language/styles pull request #5840
Opened 2022-01-13 10:49 UTC by POBrien333

I noticed it was mentioned that the ARU style has a few issues on #5633.

I fixed a few things. The guidelines are very elaborate.
https://library.aru.ac.uk/referencing/harvard.htm

2022-01-13 12:39 UTC, bwiernik requested changes

2022-01-13 12:39 UTC, bwiernik commented on harvard-anglia-ruskin-university.csl
> +    <text term="anonymous" form="short" text-case="capitalize-first" strip-periods="true" suffix="."/>
```suggestion
    <text term="anonymous" form="short" text-case="capitalize-first" strip-periods="false"/>
```

This instead, no?

2022-01-13 12:39 UTC, bwiernik commented on harvard-anglia-ruskin-university.csl
> +          <text variable="URL" prefix="&lt;" suffix=">"/>
```suggestion
          <text variable="URL" prefix="&lt;" suffix="&gt;"/>
```

This needs to be escaped.

2022-01-13 12:39 UTC, bwiernik commented on harvard-anglia-ruskin-university.csl
> +          <text macro="translator" suffix="."/>
```suggestion
          <text macro="translator"/>
```

This would make double punctuation with the group delimiter

2022-02-06 02:32 UTC, adam3smith commented
@bwiernik letting you merge this since you've already looked at the code quite a bit

2022-02-06 20:50 UTC, merged

2022-02-06 20:50 UTC, bwiernik commented
Thanks!