Update modern-language-association.csl
citation-style-language/styles pull request #5859
Opened 2022-01-19 16:43 UTC by POBrien333

closes https://github.com/citation-style-language/styles/issues/5352

2022-01-19 17:14 UTC, bwiernik commented
What does MLA say about newspapers and magazines for publisher?

2022-01-19 17:40 UTC, adam3smith commented
At least in the 8th edition, all periodicas are treated the same: no publisher, no place of publication (for local Newspapers, it can be added in square brackets after the name of the paper, but that should likely be in the data, not automated)

2022-01-19 18:15 UTC, bwiernik requested changes

2022-01-19 18:15 UTC, bwiernik commented on modern-language-association-8th-edition.csl
> +      <if type="article-journal" match="none">
```suggestion
      <if type="article-magazine article-newspaper article-journal" match="none">
```

2022-01-19 18:15 UTC, bwiernik commented on modern-language-association.csl
> +      <if type="article-journal" match="none">
```suggestion
      <if type="article-magazine article-newspaper article-journal" match="none">
```

2022-01-20 08:34 UTC, POBrien333 commented
Thanks :)

2022-01-23 11:46 UTC, merged

2022-01-23 11:48 UTC, adam3smith commented
Thanks! We should think about how to implement this more widely - with Zotero importing publishers via embedded metadata, e.g., we'll see more of this for less prominent styles