Create afnor690-2010-uco.csl
citation-style-language/styles pull request #5884
Opened 2022-02-02 14:23 UTC by Kalunna

Hello,
Here is a French adaptation of the APA standard (American Psychological Association) version of the year 2010, for the Catholic University of the West.
Thanks

2022-04-19 10:33 UTC, bwiernik requested changes
Thanks! A few comments.

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +    <link href="http://www.zotero.org/styles/afnor690-2010-uco" rel="self"/>
Please add a "template" link for the style you started with to make this adaptation.

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +-->
```suggestion
        <!-- TODO: Patent main creator should be Zotero "assignee", which is not yet available in CSL -->
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +    <!-- Called by secondary-responsability-->
```suggestion
    <!-- Called by secondary-responsibility-->
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +    <!-- FIXME : improve management of secondary responsabiliy for other types -->
```suggestion
  <macro name="secondary-responsibility">
    <!-- FIXME : improve management of secondary responsibiliy for other types -->
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +  <macro name="container-responsability">
```suggestion
  <macro name="container-responsibility">
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +    <!-- Called by secondary-responsability-->
```suggestion
    <!-- Called by secondary-responsibility-->
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +  <macro name="responsability">
```suggestion
  <macro name="responsibility">
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +                <text macro="container-responsability"/>
```suggestion
                <text macro="container-responsibility"/>
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +      <text macro="responsability"/>
```suggestion
      <text macro="responsibility"/>
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +      <!--  <text macro="secondary-responsability"/> -->
```suggestion
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +    <text variable="note" text-case="capitalize-first"/>
What is the rationale here? `"note"` should generally only be included for annotated bibliographies as it often contains a lot of information that should not be cited.

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +  <macro name="bibliography-reference">
Please remove the `citation-reference` and `bibliography-reference` macros and just put the contents directly in the `layout` section of `citation` and `bibliography`.

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +      <text macro="responsability"/>
```suggestion
      <text macro="responsibility"/>
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +      <text macro="secondary-responsability"/>
```suggestion
      <!-- secondary-responsibility : used for patent inventors and translators -->
      <text macro="secondary-responsibility"/>
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +      <key macro="responsability"/>
```suggestion
      <key macro="responsibility"/>
```

2022-04-19 10:33 UTC, bwiernik commented on afnor690-2010-uco.csl
> +          <text macro="numberOfVolumes"/>
For consistency of style, please rename the macro `number-of-volumes`.

2022-06-25 19:51 UTC, adam3smith commented
@Kalunna -- please see the above comments

2022-09-27 03:08 UTC, adam3smith commented
Closing due to inactivity -- we're happy to re-open this if you find time to come back to it: simply post a short message here.

2022-09-27 03:08 UTC, closed without merging