Update archaeonautica.csl
citation-style-language/styles pull request #5928
Opened 2022-02-25 13:18 UTC by samarkar

2022-02-25 13:35 UTC, bwiernik requested changes
Thanks! It looks like there may be some duplicated punctuation added in a few places because of the includes of the . in both prefixes and suffixes. 

For this reason, it's best practice to avoid things like `". "` as a prefix or a suffix. Instead, use a `<group delimiter=". ">`. 

For example, it would be best in this style if the bibliography looked like this:

```
 <group suffix="." delimiter=". ">
        <text macro="year-date"/>
        <text macro="title"/>
        <text macro="translator"/>
        <text macro="edition"/>
        <text macro="event"/>
        <text macro="place"/>
        <text macro="publisher"/>
        <text macro="collection"/>
        <text macro="page-bib"/>
        <text macro="archive"/>
      </group>
```

And the individual macros did not include any prefixes or suffixes holding the spaces or dots. 

Do you think you could go through the style and clean that up?

2022-02-25 13:35 UTC, bwiernik commented on archaeonautica.csl
> +    <id>http://www.zotero.org/styles/archaeonautica_encours</id>
```suggestion
    <title>Archaeonautica</title>
    <title-short>Archaeonautica</title-short>
    <id>http://www.zotero.org/styles/archaeonautica</id>
```

2022-02-25 13:39 UTC, bwiernik commented
In line 219, can you please delete `    <text term="translator" form="verb" prefix=", " suffix=" "/>` and instead use a `<label>` inside the `<names>` element?

2022-02-25 18:03 UTC, samarkar commented
Dear Brenton, thank you very much for your patience and your careful proofreading. I am correcting the style according to your indications but, concerning your last remark, what is your suggestion? I would like to keep the possibility of automatic translation of the  name variable Translator.

2022-04-19 09:52 UTC, bwiernik commented
@samarkar Sorry on the delay. You have misunderstood. A `<label>` is still automatically translated. `<label>` is appropriate way to add role terms to a name.

2022-04-19 09:58 UTC, bwiernik commented
@samarkar The `<label>` is now fine as-is.

However, looking at the example citations rendered above, there are several formatting issues (e.g., in the first example, there is no space between "Editor." and the URL). I would like you to please go through the style carefully and consistently use groups and delimiters to control punctuation and spaces, rather than prefixes/suffixes. Please carefully test your style to ensure that the output is correct.

2022-06-26 18:34 UTC, merged

2022-06-26 18:34 UTC, adam3smith commented
I fixed the missing space before the URL. Would indeed be good to take a closer look at this, but overall this seems like an improvement, so taking it.