Update urad-rs-za-makroekonomske-analize-in-razvoj.csl
citation-style-language/styles pull request #5963
Opened 2022-03-14 12:34 UTC by majazaloznik

Minor changes to delimiters for presentation entry type.

2022-03-24 01:29 UTC, adam3smith requested changes
Thanks! 2 small things. Looks good otherwise .

2022-03-24 01:29 UTC, adam3smith commented on urad-rs-za-makroekonomske-analize-in-razvoj.csl
> +            <number variable="number-of-volumes" form="numeric" prefix="11&#8211;"/>
This is a typo, right? It should stay 1?

2022-03-24 01:29 UTC, adam3smith commented on urad-rs-za-makroekonomske-analize-in-razvoj.csl
> +                        <if match="any" variable="genre">
The test here is unnecessary. text variable implicitly test for the variable's presence

2022-03-24 01:52 UTC, adam3smith commented
(test comment, please ignore)

2022-04-11 16:37 UTC, merged

2022-04-11 16:37 UTC, bwiernik commented
Thanks!

2022-04-11 22:20 UTC, majazaloznik commented
Thank you!