Fix annales-medico-psychologiques
citation-style-language/styles pull request #5997
Opened 2022-03-30 07:55 UTC by symac

Up to this PR, annales-medico-psychologiques was a dependent style of elsevier-vancouver. But the [instructions to authors](https://www.elsevier.com/journals/annales-medico-psychologiques-revue-psychiatrique/0003-4487/guide-for-authors) indicate that references should be alphabetically sorted, which can be confirmed by looking at articles from this journal where references are numbered based on the author alphabetically sorted list rather than the order of appearance in the article.

This PR is removing the dependent style and creating a new one that is mainly a copy of the elsevier-vancouver one, adding a sort option in the bibliography.

2022-03-30 08:46 UTC, denismaier requested changes

2022-03-30 08:46 UTC, denismaier commented on annales-medico-psychologiques.csl
> +      <key variable="author" sort="ascending"/>
I think you should add a second sort key if the author key is identical. (Probably using `title`?)

2022-03-30 08:46 UTC, denismaier commented on annales-medico-psychologiques.csl
> +      <key variable="author" sort="ascending"/>
Also, check how references without authors are sorted.

2022-04-19 09:26 UTC, bwiernik commented
@symac Can you please address the questions above? Thanks!

2022-07-03 14:57 UTC, adam3smith commented
@symac -- I'm closing here to keep our PR queue manageable. Happy to re-open, just let us know by leaving a comment here.

2022-07-03 14:57 UTC, closed without merging