Update guide-des-citations-references-et-abreviations-juridiques.csl
citation-style-language/styles pull request #6002
Opened 2022-04-05 20:09 UTC by rafjaf

Abbreviate "traduit par" in "trad."

2022-04-05 22:09 UTC, bwiernik requested changes
Thanks! This should actually be shown by using the `label` element rather than using a prefix.

2022-04-05 22:09 UTC, bwiernik commented on guide-des-citations-references-et-abreviations-juridiques.csl
> +      <name font-style="normal" prefix=" trad. " and="text" delimiter-precedes-last="never" sort-separator=" ">
```suggestion
      <name font-style="normal" and="text" delimiter-precedes-last="never" sort-separator=" ">
        <label form="verb-short"/>
```

2022-04-07 07:19 UTC, rafjaf commented
Thank you very much. I am sorry to ask, but what should I do next?
Rafaël



> Le 6 avr. 2022 à 00:10, Brenton M. Wiernik ***@***.***> a écrit :
> 
> 
> @bwiernik requested changes on this pull request.
> 
> Thanks! This should actually be shown by using the label element rather than using a prefix.
> 
> In guide-des-citations-references-et-abreviations-juridiques.csl <https://github.com/citation-style-language/styles/pull/6002#discussion_r843302455>:
> 
> > @@ -57,7 +57,7 @@
>    </macro>
>    <macro name="translator">
>      <names variable="translator">
> -      <name form="long" and="text" delimiter-precedes-last="never" sort-separator=" " font-style="normal" prefix=" traduit par ">
> +      <name font-style="normal" prefix=" trad. " and="text" delimiter-precedes-last="never" sort-separator=" ">
> ⬇️ Suggested change
> -      <name font-style="normal" prefix=" trad. " and="text" delimiter-precedes-last="never" sort-separator=" ">
> +      <name font-style="normal" and="text" delimiter-precedes-last="never" sort-separator=" ">
> +        <label form="verb-short"/>
> —
> Reply to this email directly, view it on GitHub <https://github.com/citation-style-language/styles/pull/6002#pullrequestreview-932571377>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAQNMPUTGCHXDYMUABS3VVDVDS24FANCNFSM5ST3KYNA>.
> You are receiving this because you authored the thread.
>

2022-04-07 21:06 UTC, rafjaf reviewed
I agree with the change. What should I do next?

2022-04-07 22:25 UTC, bwiernik commented
I'll take care of it

2022-04-19 09:42 UTC, merged

2022-04-19 09:42 UTC, bwiernik commented
Thanks! Sorry on the delay.

2022-10-11 09:00 UTC, rafjaf commented
No problem, and thank you for your work!



> Le 19 avr. 2022 à 11:42, Brenton M. Wiernik ***@***.***> a écrit :
> 
> 
> Thanks! Sorry on the delay.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/citation-style-language/styles/pull/6002#issuecomment-1102400265>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAQNMPWYU2UJFEHYYGBZ3ATVFZ5YDANCNFSM5ST3KYNA>.
> You are receiving this because you modified the open/close state.
>