Create intellect-newgen-style.csl
citation-style-language/styles pull request #6007
Opened 2022-04-06 10:08 UTC by amyrolla

First CSL file for Intellect Books (sorry I placed this in dependent first by mistake)

2022-04-14 13:37 UTC, bwiernik requested changes
Thanks for the submission!

A few notes to start:

1. Can you please add a "documentation" link to the style guidelines online?
2. Did you start from scratch or by modifying another style? Can you please add a "template" link for the style that you started with to edit?
3. Please don't hard-code in format/type data. Expect that to be in the `medium` or `genre` variables.
4. There are a bunch of apparent errors with author names included in the style. Please double check all of that.
5. You have a bunch of prefixes and suffixes with things like `, `. These should be groups with delimiters instead.

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +    <title>Intellect Newgen Style</title>
```suggestion
    <title>Intellect Newgen Books</title>
```

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +    <summary>Style for Intellect Newgen Style</summary>
```suggestion
    <summary>Style for Intellect Newgen Books</summary>
```

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +    <link href="http://www.zotero.org/styles/intellect-newgen-style" rel="self"/>
Add "template" and "documentation" links please

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +      </if>
Should the publication year (`issued`) also be included when `original-date` is present?

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +                  <label variable="edition" form="short"/>
What exactly is this for? In general, hardcoding these words seems inappropriate (what if the citation is not to a DVD?). I would suggest instead printing the `genre` variable and expecting this information to be in the item data.

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +                <text value="installation" prefix=", "/>
Art exhibits should be cited using type `event`, rather than `graphic`.

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +                  <text value=" L. Bernstein), "/>
What is this for?

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +                <text value="exhibition catalogue" prefix=", "/>
This should not be hard-coded. The appropriate item type for an exhibition catalogue is `book`.

2022-04-14 13:37 UTC, bwiernik commented on intellect-newgen-style.csl
> +                    <text value="review" prefix=", "/>
Use `term="review"`

2022-04-19 07:54 UTC, POBrien333 commented
See also this open PR for this style: https://github.com/citation-style-language/styles/pull/5918

2022-04-19 07:56 UTC, bwiernik commented
@amyrolla Can you please update your style per my reviews above? Please edit the style in the PR. Do not open a new PR

2022-04-19 09:16 UTC, amyrolla commented
Apologies! I'm getting the style updated with our developers and will update the PR asap

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Brenton M. Wiernik ***@***.***>
Sent: Tuesday, April 19, 2022 8:56:42 AM
To: citation-style-language/styles ***@***.***>
Cc: amyrolla ***@***.***>; Mention ***@***.***>
Subject: Re: [citation-style-language/styles] Create intellect-newgen-style.csl (PR #6007)


@amyrolla<https://github.com/amyrolla> Can you please update your style per my reviews above? Please edit the style in the PR. Do not open a new PR

—
Reply to this email directly, view it on GitHub<https://github.com/citation-style-language/styles/pull/6007#issuecomment-1102237284>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYSVRYCPURF5PRCKAI6C3ODVFZRLVANCNFSM5SVQGTRA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-27 03:09 UTC, adam3smith commented
Closing due to inactivity -- we're happy to re-open this if you find time to come back to it: simply post a short message here.

2022-09-27 03:09 UTC, closed without merging