Style for Acta Physica Sinica (物理学报)
citation-style-language/styles pull request #6009
Opened 2022-04-07 01:01 UTC by redleafnew

Style for Acta Physica Sinica (物理学报) https://wulixb.iphy.ac.cn/news/tougaoxuzhi.htm

2022-04-07 13:01 UTC, adam3smith requested changes
Some requested changes -- biggest concern is the title-short for language, which is IMO not a good way of handling this.

2022-04-07 13:14 UTC, redleafnew commented on acta-physica-sinica.csl
> +    <link href="https://wulixb.iphy.ac.cn/news/tougaoxuzhi.htm" rel="documentation"/>
Yes, I started this template style, with short title contain the translated version of the item.
And some other styles I created used this methold such as <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/14tcsae.csl>, however, there are two layouts, which is not allowed in cls 1.01 and only support by Jurism.

2022-04-07 13:19 UTC, redleafnew commented on acta-physica-sinica.csl
> +      <substitute>
I have no idea about this either, I have not submit a paper to this journal, only the authors and traslators are needed in the guidelines and some other example articles I downloaded from it's website.

2022-04-07 13:25 UTC, redleafnew commented on acta-physica-sinica.csl
> +  <bibliography entry-spacing="0" et-al-min="10000" et-al-use-first="1000" second-field-align="flush">
ok, I will edit the file.

2022-04-07 13:28 UTC, redleafnew commented on acta-physica-sinica.csl
> +      <if variable="title-short">
the original-title field could not be found in Zotero, put this in the Extra?

2022-04-07 13:34 UTC, redleafnew commented on acta-physica-sinica.csl
> +        <text variable="title-short" suffix="(in Chinese) ["/>
Does it like this <code><group delimiter=" " prefix="["=""></code>

2022-04-07 13:54 UTC, redleafnew commented on acta-physica-sinica.csl
> +      <if variable="title-short">
` original-title` is a CSL variable has no corresponding Zotero field.

2022-04-07 14:28 UTC, redleafnew commented on acta-physica-sinica.csl
> +        <text variable="title-short" suffix="(in Chinese) ["/>
Using `suffix="]"` in the group will produce a un necessary` ']'` if there is no `original-title` or space if there is `original-title`

2022-04-07 14:43 UTC, redleafnew commented on acta-physica-sinica.csl
> +        <text variable="title-short" suffix="(in Chinese) ["/>
And using ` <group delimiter=" " prefix="[">` will produce a un necessary '[' if there is no `original-title`, so I think I have to change back to `suffix="(in Chinese) ["/`

2022-04-08 03:50 UTC, redleafnew commented
I have changed the file structure with  `<text variable="title-short" suffix=" (in Chinese)" />` and  `<group delimiter=" " prefix=" [" suffix="]">`,  and delete et al min which hope to meet the requirement.

2022-04-08 11:55 UTC, bwiernik commented on acta-physica-sinica.csl
> +    <link href="https://wulixb.iphy.ac.cn/news/tougaoxuzhi.htm" rel="documentation"/>
What he means is please add a link to the style you modified here with `relation="template"`. This is to acknowledge the work of the author of that style and track relationships among styles

2022-04-08 12:30 UTC, redleafnew reviewed
fixed

2022-04-08 12:30 UTC, redleafnew commented on acta-physica-sinica.csl
> +    <link href="https://wulixb.iphy.ac.cn/news/tougaoxuzhi.htm" rel="documentation"/>
Got it, the link was added.

2022-04-08 12:59 UTC, bwiernik commented
@adam3smith You've already looked at this, so I will let you finish

2022-04-08 13:09 UTC, redleafnew commented
thanks.

2022-04-12 00:47 UTC, redleafnew commented
Any change requested?

2022-04-22 14:11 UTC, redleafnew commented
Any change requested?
@adam3smith

2022-04-24 14:24 UTC, merged

2022-04-24 14:25 UTC, adam3smith commented
Sorry for the delay & thanks!