Create belin-agregation.csl
citation-style-language/styles pull request #6090
Opened 2022-06-14 10:13 UTC by yanbabels

I adapted the ENS de Lyon style to have different citation elements that correspond to what the publisher BELIN uses for its AGREGATION series

2022-06-14 11:12 UTC, yanbabels commented
I just realized I added 'ENGLISH' but this style hasn't been localized yet and is in FRENCH

2022-06-25 19:12 UTC, adam3smith requested changes
A couple of small things -- also see damnation's comment above

2022-06-25 19:12 UTC, adam3smith commented on belin-agregation.csl
> +    <link href="http://cid.ens-lyon.fr/articles/zotero_style_cid.pdf" rel="documentation"/>
could you link to the documentation for Belin here?

2022-06-25 19:12 UTC, adam3smith commented on belin-agregation.csl
> +      <name>Yan Brailowsky</name>
Please make yourself the main author, even if you only changed a few things.

2022-08-24 01:54 UTC, adam3smith commented
@yanbabels please see the questions above

2022-09-27 03:11 UTC, adam3smith commented
Closing due to inactivity -- we're happy to re-open this if you find time to come back to it: simply post a short message here.

2022-09-27 03:11 UTC, closed without merging

2022-10-11 07:33 UTC, yanbabels commented
hi,
basically, yes, although I did one minor change (putting idem instead of 
id). The problem is I don't know how to add the locale… I'm new to this, 
as you can see.
Is there a simple way to add the EN localization in the original file? I 
read the documentation online and I still don't get it.
Best
Yan

On 15/6/22 11:58, POBrien333 wrote:
> Your two PRs are for the exact same style, but just with a different 
> language?
> In that case you'd just remove the locale and add a polyglot line as 
> seen here in line 3: 
> https://github.com/citation-style-language/styles/blob/master/crustaceana.csl 
> <https://github.com/citation-style-language/styles/blob/master/crustaceana.csl>
> 
> Please edit this PR here and close the other one then.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/citation-style-language/styles/pull/6090#issuecomment-1156260875>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AZT6RUTY2PACNUDABSBFV5TVPGSLHANCNFSM5YXENI5Q>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>