Create pallas.csl
citation-style-language/styles pull request #6204
Opened 2022-09-02 08:49 UTC by Oxil-2

CSL style for the French Classics and Ancient History journal "Pallas - Revue d'études antiques", https://journals.openedition.org/pallas/

2022-10-12 02:35 UTC, adam3smith requested changes
I didn't go line-by-line here, but this has very much the same issues I noted in your stylesheet for Mots, so please also address those. Thanks!

2022-10-12 02:35 UTC, adam3smith commented on pallas.csl
> +    <link href="https://journals.openedition.org/pallas/2624" rel="documentation"/>
any template style used here?

2022-10-12 02:35 UTC, adam3smith commented on pallas.csl
> +        <names variable="editor" font-variant="small-caps"/>
no need for the font-variant, that's inherited from authors.

2022-10-12 02:35 UTC, adam3smith commented on pallas.csl
> +      </substitute>
you almost certainly want to add title here to correspond to the in-text citation (also look at the weird webpage example in the preview)

2022-11-11 17:53 UTC, Oxil-2 commented
Just made all changes accordingly

2022-11-12 22:29 UTC, merged

2022-11-12 22:29 UTC, adam3smith commented
Looks great, thanks!