Create mots.csl
citation-style-language/styles pull request #6205
Opened 2022-09-02 08:52 UTC by Oxil-2

CSL style for the French journal "Mots - Les langages du politique" (politics, linguistics, communication studies), cf. https://journals.openedition.org/mots/

2022-09-02 09:29 UTC, POBrien333 commented on mots.csl
> +    <link href="http://www.zotero.org/styles/mots" rel="self"/>
please add the style you used as a template as indicated here: https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#csl-style-repository-requirements

2022-10-12 02:27 UTC, adam3smith requested changes
Thanks & sorry for the slow review -- a number of comments inline

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +        <names variable="editor">
why are you using these elaborate substitutes instead of just `<names variable="editor"/>` (the other elements are inherited from author)

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +      <key macro="contributeurs-tri"/>
I don't understand the difference between the auteurs macro and this one -- they seem redundant. Why not just sort by `auteurs`?

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +            <if variable="author">
No need for these tests -- they are implicitly in `substitute` above

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +        <group delimiter=", ">
don't use groups with only one element inside

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +        <group delimiter=", ">
same here with groups

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +          <group prefix="(consulté le " suffix=")">
it's much preferred to avoid hardcoding strings and using (and if necessary re-defining) terms instead.

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +            <text variable="locator" prefix="p. "/>
You definitely want to use a label for the locator, since that can also be other things than page (like chapter, column, etc.)

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +          <if locator="page" match="none">
why do you need this test if you're then printing the p. for pages anyway?

2022-10-12 02:27 UTC, adam3smith commented on mots.csl
> +            <if variable="author">
again, you don't need these tests because of substitute

2022-10-24 09:22 UTC, Oxil-2 commented
> Thanks & sorry for the slow review -- a number of comments inline

Thank you so much for the review. I've tried to correct the errors and just pulled an updated file.

2022-11-02 02:38 UTC, merged

2022-11-02 02:39 UTC, adam3smith commented
Thanks, this looks great now -- yes, please do adjust the other two along similar lines.