Add space before pp
citation-style-language/styles pull request #6343
Opened 2022-12-20 14:03 UTC by EricMarcon

The sample 
>Mares, I (2001) Firms and the welfare state: When, why, and how does social policy matter to employers? In P. A. Hall and D. Soskice, eds., Varieties of capitalism. The institutional foundations of comparative advantage, New York: Oxford University Presspp. 184–213.

had no space between "Oxford University Press" and "pp. 184–213."

2022-12-20 17:16 UTC, bwiernik requested changes
Thanks! Let's also add a comma

2022-12-20 17:16 UTC, bwiernik commented on cambridge-university-press-author-date.csl
> +                <label variable="page" form="short" prefix=" " suffix=" "/>
```suggestion
                <label variable="page" form="short" prefix=", " suffix=" "/>
```

2022-12-22 08:47 UTC, EricMarcon commented
Done.

2022-12-30 21:03 UTC, merged

2022-12-30 21:03 UTC, adam3smith commented
Thanks!