Create folia-amazonica.csl
citation-style-language/styles pull request #6418
Opened 2023-02-20 21:45 UTC by RAGMA96

Citation Style for Folia Amazónica- Instituto de Investigaciones de la Amazonía Peruana

2025-03-05 01:39 UTC, adam3smith requested changes

2025-03-05 01:39 UTC, adam3smith commented on folia-amazonica.csl
> +    <link href="https://www.entecho.cz/cs-cz/o-casopisu/pokyny-pro-autory" rel="documentation"/>
```suggestion
    <link href="https://revistas.iiap.gob.pe/index.php/foliaamazonica/guia_autores" rel="documentation"/>
```

2025-03-05 01:39 UTC, adam3smith commented on folia-amazonica.csl
> +<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" demote-non-dropping-particle="never" default-locale="en-US">
```suggestion
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" demote-non-dropping-particle="never">
```

2025-03-05 01:39 UTC, adam3smith commented on folia-amazonica.csl
> +        <text value=" En" text-case="capitalize-first" suffix=": "/>
```suggestion
        <text term="in" text-case="capitalize-first" prefix=" " suffix=": "/>
```

2025-03-05 01:39 UTC, adam3smith commented on folia-amazonica.csl
> +      <label form="short" prefix=" (" suffix=")" text-case="capitalize-first"/>
```suggestion
      <label form="short" prefix=" (" suffix=")" text-case="capitalize-first" strip-periods="true"/>
```

2025-03-05 01:39 UTC, adam3smith commented on folia-amazonica.csl
> +      <name form="short" and="symbol" initialize-with=". "/>
```suggestion
      <name form="short" and="symbol" initialize-with=". ">
<et-al font-style="italic"/>
</name>
```

2025-03-06 14:35 UTC, bwiernik requested changes

2025-03-06 15:09 UTC, RAGMA96 commented
@bwiernik There are double dots between the year of publication and the title. Could you help me to solve this, please?

2025-03-06 17:49 UTC, bwiernik commented
Can you check the style in Zotero or pandoc and see if the issue shows up there?

2025-03-06 19:08 UTC, RAGMA96 commented
> Can you check the style in Zotero or pandoc and see if the issue shows up there?

I've jut checked, and it seems to work fine. Thanks

2025-07-16 15:46 UTC, POBrien333 commented
@RAGMA96 
I just reworked your style and fixed a whole bunch of issues. Please test it out and hopefully we can then merge it.

2025-07-18 21:17 UTC, RAGMA96 commented
> @RAGMA96 I just reworked your style and fixed a whole bunch of issues. Please test it out and hopefully we can then merge it.

Seems to work fine

2025-07-18 21:50 UTC, POBrien333 commented
Can you go here and click on Sync fork up top?
That should remove the validation errors.
https://github.com/RAGMA96/styles/tree/patch-1

2025-07-18 22:01 UTC, RAGMA96 commented
> Can you go here and click on Sync fork up top? That should remove the validation errors. https://github.com/RAGMA96/styles/tree/patch-1

Already done

2025-07-19 07:16 UTC, merged