Update united-states-international-trade-commissio
citation-style-language/styles pull request #6487
Opened 2023-03-30 16:54 UTC by USITC-Zotero

Changelog summary:

-	Added code to support new item types, such as hearing, interview, and software (i.e., databases) 
- 	Updated Zotero styles to conform to Editors guidance document 
- 	Various bug fixes for Blogs, Book, Book Sections, Broadcasts, Presentations, and Videos item types. 
- 	Resolved title conflicts between blog and webpage titles that may not be put in the author field

2023-03-31 03:07 UTC, adam3smith requested changes
A couple of questions, one change request: please do clean up all those title-short tests: they're not necessary and add lots of unnecessary and hard to read code.

2023-03-31 03:07 UTC, adam3smith commented on united-states-international-trade-commission.csl
> +            </choose>
```suggestion
            <text variable="title" form="short"/>
```
does the exact same thing as this whole test. ditto below -- please change accordingly

2023-03-31 03:07 UTC, adam3smith commented on united-states-international-trade-commission.csl
> +            <text variable="title-short" quotes="true"/>
the difference with respect to quotation marks for short & full title here is on purpose?

2023-03-31 03:07 UTC, adam3smith commented on united-states-international-trade-commission.csl
> +          <text value="Warning: the 'extra' field does not populate correctly with presentation citation item types. Please edit this citation item in the Zotero app to resolve. A manual overwrite ma
what's going on there? That seems like something that should get fixed, maybe at Zotero?

2023-04-05 12:54 UTC, adam3smith commented
Thanks. You can ignore any local testing error. Only the test on the PR itself is relevant (the release action shouldn't even run in your fork, but it also doesn't do any harm)

2023-04-05 16:59 UTC, USITC-Zotero commented
Apologies, if I wasn't supposed to "request a draft." I saw that the bot had a label requesting an action from the contributor that I presumed was aimed at me.

2023-04-06 14:20 UTC, USITC-Zotero reviewed
Not sure if the draft status of this pull request is correct. I'll submit the draft for review

2023-04-15 03:01 UTC, merged

2023-04-15 03:01 UTC, adam3smith commented
Thanks!