Corrected in line with test results
citation-style-language/styles pull request #6643
Opened 2023-08-17 23:54 UTC by mickmorrison

2023-09-25 02:21 UTC, adam3smith requested changes
Thanks -- quick issue above.
For future reference, please don't make PRs from your main/master branch: it prevents us from making any fixes and prevents our bot from fixing the formatting. Please run the style through formatter.citationstyles.org/ 
Our standard instructions will automatically create a feature branch for your PRs.

2023-09-25 02:21 UTC, adam3smith commented on australian-archaeology.csl
> +<style class="in-text" version="1.0" sort-separator=" " demote-non-dropping-particle="sort-only" default-locale="en-GB" xmlns="http://purl.org/net/xbiblio/csl">
```suggestion
<style class="in-text" version="1.0" demote-non-dropping-particle="sort-only" default-locale="en-GB" xmlns="http://purl.org/net/xbiblio/csl">
```

The `sort-separator=" "` removes the comma before initials for first authors, which is incorrect.

2025-08-12 03:09 UTC, closed without merging

2025-08-12 16:52 UTC, bwiernik commented
@mickmorrison did you intend to close this?

2025-08-13 04:40 UTC, mickmorrison commented
@bwiernik yes, I deleted yesterday as they were old contributions hanging around at my end, that were in error and superseded by subsequent commits. Apologies if that is an error or a problem for you or others?

2025-08-13 14:32 UTC, bwiernik commented
No problem, just checking that it wasn't accidental. Thank you for your contributions!