Create modern-language-association-annotated-bibliography.csl
citation-style-language/styles pull request #6717
Opened 2023-09-28 23:56 UTC by calumapplepie

Note: this style currently fails to render with hanging indents for an unknown reason.  I tested with Libreoffice, for the record

2023-09-29 02:26 UTC, bwiernik requested changes
Thanks! I made a comment for how to fix the indenting

2023-09-29 02:26 UTC, bwiernik commented on modern-language-association-annotated-bibliography.csl
> +      <text variable="note" display="indent"/>
```suggestion
      <text variable="note" display="block"/>
```

2023-09-29 02:56 UTC, adam3smith commented
I haven't tested, but I thought the display elements don't work well with formatting added through cs:bibliography (like hanging-indent="true") here?

I'll generally say that I'm still quite skeptical about including annotated bibliographies beyond the two we already have. It's a rabbit hole of possible additions that all vary in three lines of code & require maintenance.

2023-09-29 16:09 UTC, calumapplepie commented
> Thanks! I made a comment for how to fix the indenting 

The indentation problem isn't that the note has a first-line indent: that was an intentional choice on my part, to set the note apart from the citation.  The problem is that the _citation_ lacks a hanging indent as a result of the display problems

2023-09-29 16:14 UTC, calumapplepie commented
> I haven't tested, but I thought the display elements don't work well with formatting added through cs:bibliography (like hanging-indent="true") here?

It doesn't, no, and I mention the limitation in my style description

> I'll generally say that I'm still quite skeptical about including annotated bibliographies beyond the two we already have. It's a rabbit hole of possible additions that all vary in three lines of code & require maintenance.

That's true, but MLA is probably one of the most used styles in education, which is where a lot of people are tasked with creating annotated bibliographies in a PDF form.  I personally have been asked to make such a document thrice in three different courses, always in MLA format.

While the combinationatorial explosion is problematic, I don't think most styles will want, need, or get this additional form.  It's really only in an educational setting where you need to produce annotated bibliographies as standalone documents, as opposed to just reading the "notes" section in Zorero.

2023-09-30 02:43 UTC, bwiernik commented
I think MLA is a reasonable one to add. It's probably the most common format requested of students after APA (eg many US high school students).

2023-10-01 19:28 UTC, calumapplepie commented
I intentionally used display=indent, as opposed to the display=block added by @bwiernik .  The indent added isn't the problem I mention and face.  I want the note block to be indented; the problem is making it display as a block *at all* causes the citation to lose its hanging indent.

With display=indent:
![image](https://github.com/citation-style-language/styles/assets/13556193/037f6da3-aee4-402c-84c9-e53cbc73ef65)

With display=block:
![image](https://github.com/citation-style-language/styles/assets/13556193/df3e1a16-d67a-4cf2-a48a-45b1c75ab7a3)

Without either:
![image](https://github.com/citation-style-language/styles/assets/13556193/2ff66f4d-f6ea-4e6c-b732-85c77eab84a9)

The ideal layout would probably be:
![image](https://github.com/citation-style-language/styles/assets/13556193/fb57c6bc-b80c-4a5a-b9c8-273c67374194)

But I see no way to accomplish that.

2023-10-01 20:53 UTC, bwiernik commented
What program are you using to generate your bibliographies?

As @adam3smith mentions, the display behavior depends somewhat on the environment in which the citation is rendered. I don't see the behavior you describe with Zotero. 

With display="block" using Zotero's Word plugin or RTF export (hanging indent with annotation aligned with hanging):
![image](https://github.com/citation-style-language/styles/assets/4773225/4c8f4901-b026-4e00-86bf-268526d96ac8)

With display="block" using Zotero's direct HTML export (hanging indent with annotation aligned with margin, with its own hanging indent): 
![image](https://github.com/citation-style-language/styles/assets/4773225/aca79342-ef7a-4aae-8413-5f202873f41f)

With display="indent" and html output, I see a hanging indent and then further indenting of the annotation:
![image](https://github.com/citation-style-language/styles/assets/4773225/e6060d63-9718-46f9-a2db-5e8200d4970d)

With display="indent" and the Word plugin or RTF output, I see no hanging indent and the annotation indented:
![image](https://github.com/citation-style-language/styles/assets/4773225/48c974c4-ae45-4a78-bf1d-f7305b1ce484)

2023-10-01 20:54 UTC, bwiernik commented
Based on this behavior and precedent with the existing annotated bibliography styles, display="block" is what should be used.

2023-11-04 20:09 UTC, calumapplepie commented
Appolgies, this fell off my to-do list.  I used Libreoffice; if the behavior can't be reproduced in other programs, I'll use display=block.

Maybe someone should look into making hanging-indent behavior more consistent, possibly by making it less of a special-case.

2023-12-16 04:45 UTC, calumapplepie commented
I believe this is in the state that @bwiernik desired, after the above force-push; if not, I am comfortable with the changes requested, now that I know it's a libreoffice-specific issue.  Thank you!

2025-07-14 15:11 UTC, merged