Create forestry.csl
citation-style-language/styles pull request #6913
Opened 2024-02-19 11:11 UTC by POBrien333

https://forums.zotero.org/discussion/103378/style-request-forestry-an-international-journal-of-forest-research-oxford-academic#latest

Public papers: https://academic.oup.com/forestry/issue/97/1

2024-08-27 19:39 UTC, bwiernik commented
@POBrien333 Looks like there's an issue with an extra ` .` being added between title and container title for website and journal items? Could you look into that?

2024-08-27 19:41 UTC, bwiernik requested changes

2024-08-27 19:41 UTC, bwiernik commented on forestry.csl
> +        <group prefix=". " delimiter=", ">
```suggestion
        <group delimiter=", ">
```

I think this can just be removed?

2024-08-29 12:25 UTC, merged

2024-08-30 07:46 UTC, POBrien333 commented
Thank you for getting PRs merged :)