Update archaeonautica.csl
citation-style-language/styles pull request #7037
Opened 2024-05-05 15:14 UTC by samarkar

I made some changes to this style but only just realized that they were not taken into account in the Zotero repository. I'm not very comfortable with Github and I certainly made some mistakes, I apologize for that.

2024-09-10 13:43 UTC, bwiernik requested changes
Thanks! For the creator role labels, please use `<label>` inside of `<names>`, rather than `<text term="..."/>` to avoid the terms being printed when those creators are not present (see the example website citation in the message above).

2024-09-10 13:43 UTC, bwiernik commented on archaeonautica.csl
> +      </name>
```suggestion
      <label form="verb" suffix=" "/>
      <name form="long" and="text" delimiter-precedes-last="never" sort-separator=" " font-style="normal">
        <name-part name="family" font-variant="small-caps"/>
      </name>
```

2024-09-10 13:43 UTC, bwiernik commented on archaeonautica.csl
> +    <text term="translator" form="verb" prefix=", " suffix=" "/>
```suggestion
```

2025-07-30 08:38 UTC, POBrien333 commented
@samarkar 
Could you please go [here](https://github.com/samarkar/styles/tree/patch-11) and click on "Sync fork"? Thanks

2025-08-25 10:58 UTC, merged