Update harvard-university-for-the-creative-arts.csl
citation-style-language/styles pull request #7153
Opened 2024-08-06 10:57 UTC by ibadger

Add variable Director, previously had used only Author but this wasn't displaying the Director in references produced in Zotero. If there is a better way to do it do let me know

2024-08-07 13:51 UTC, bwiernik requested changes
Thanks, I updated to use a more robust approach.

2024-08-07 13:51 UTC, bwiernik commented on harvard-university-for-the-creative-arts.csl
> +        <names variable="author director" delimiter=" " prefix="Directed by ">
```suggestion
        <names variable="director">
          <label variable="director" text-case="capitalize-first" suffix=" "/>
```

2024-08-20 15:00 UTC, ibadger commented
I added a Macro for Director and resubmitted, it seemed to validate but am unsure if it is the best way to go about it. Sorry for the delay I have been away from work, and am a bit slow when it comes to coding

2024-10-07 13:30 UTC, ibadger commented
I made some changes a while ago, but forgot about it  - does it work now?

2024-10-25 15:56 UTC, closed without merging