Create melanges-de-linstitut-dominicain-detudes-orientales-en.csl
citation-style-language/styles pull request #7230
Opened 2024-09-29 11:21 UTC by NicolasSouchon

Create a new CSL style for the Mélanges de l'Institut dominicain d'études orientales collection (English Version, documentation here: https://journals.openedition.org/mideo/9227)

2024-09-29 22:22 UTC, bwiernik commented
Thanks! Are the English and French versions identical other than the default language?

2024-09-30 05:39 UTC, NicolasSouchon commented
The English and French versions are practically identical, apart from few elements that I can't change with a single style (italics on the _in_ in French, comma before the _in_ in English and different square brackets in French and English)

2025-01-16 21:43 UTC, bwiernik requested changes
Thanks for your patience. I've made a few revisions to align the style with the documentation you linked to (e.g., formatting of issued/orginal-date) and to add correct substitution when an item doesn't have an author. 

Could you please make the same changes to the French style?

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +    </names>
```suggestion
      <substitute>
        <names variable="editor translator"/>
        <text variable="title"/>
      </substitute>
    </names>
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +          <if type="chapter" match="any">
```suggestion
          <if type="chapter entry entry-dictionary entry-encyclopedia" match="any">
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +            </choose>
```suggestion
            <text macro="date"/>
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +  <macro name="url">
```suggestion
  <macro name="date">
    <choose>
      <if match="any" variable="original-date">
        <group delimiter="/">
          <text macro="original-date"/>
          <text macro="issued" prefix="[" suffix="]"/>
        </group>
      </if>
      <else>
        <text macro="issued"/>
      </else>
    </choose>
  </macro>
  <macro name="url">
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +            </choose>
```suggestion
            <text macro="date"/>
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +          <else-if type="webpage" match="any">
```suggestion
          <else-if type="webpage article" match="any">
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +      <names variable="editor">
```suggestion
      <names variable="editor translator">
```

2025-01-16 21:43 UTC, bwiernik commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +    <title>Mélanges de l'Institut dominicain d'études orientales (english)</title>
```suggestion
    <title>Mélanges de l'Institut dominicain d'études orientales (English)</title>
```

2025-01-26 06:28 UTC, NicolasSouchon commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +          <if type="chapter" match="any">
There are differences in the way chapters and dictionary/encyclopaedia entries are treated, such as the treatment of the _in_ or the container-title, so we should leave the treatment of these categories separate

2025-01-26 06:31 UTC, NicolasSouchon commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +          <else-if type="webpage" match="any">
I prefer to leave the treatment of the article category in the else instruction, which applies to all categories not described above

2025-01-26 06:35 UTC, NicolasSouchon commented on melanges-de-linstitut-dominicain-detudes-orientales-en.csl
> +  <macro name="url">
A few corrections need to be made here. There is no / between the original-date and the issued, which is used in the recommendations to separate the years of the hegira from those of the Christian calendar. Next, the original-date should appear in square brackets after the issued

2025-01-26 06:42 UTC, NicolasSouchon reviewed
Thanks, I have made the corrections requested, with the exception of a few justified in the comments.

2025-05-10 14:48 UTC, NicolasSouchon commented
@bwiernik Can you tell me if the requested corrections are enough and if this style and its French version can be added to the Zotero style library?

2025-09-14 16:14 UTC, merged