Create neues-jahrbuch-fur-geologie-und-palaontologie.csl
citation-style-language/styles pull request #7252
Opened 2024-10-10 08:01 UTC by POBrien333

https://forums.zotero.org/discussion/118403/style-request-neues-jahrbuch-fuer-geologie-und-palaeontologie-abhandlungen#latest

2024-10-20 16:46 UTC, bwiernik commented
Thanks! Should “(eds.)” appear in text when substituting, and does the style call explicitly for “anonymous” for un-authored items? If not, let’s substitute title

2024-10-21 08:27 UTC, POBrien333 commented
The "(eds.)" I don't know. It's not in the guidelines and not in the example paper I looked at.
I've taken the anonymous out. That's just from the template style.
I tend to leave things as is unless I have a reason to change it.

2025-03-01 15:56 UTC, adam3smith requested changes

2025-03-01 15:56 UTC, adam3smith commented on neues-jahrbuch-fur-geologie-und-palaontologie.csl
> +      <label form="short" prefix=" (" suffix=")"/>
```suggestion
```

2025-03-02 00:52 UTC, merged