Fix unsupported unicode characters in two styles
citation-style-language/styles pull request #7274
Opened 2024-10-21 00:10 UTC by mdmower

Fix invalid unicode characters in the following styles:

`journal-of-the-marine-biological-association-of-the-united-kingdom.csl`

- From PR #2547, it looks like the original style was cloned from `apa-6th-edition.csl`. The invalid character in `number-of-volumes` was updated to match that journal: `&#8211;`.

`museum-national-dhistoire-naturelle.csl`

- Overwhelmingly, styles use the following within the `genre` macro:
  ```
  <text variable="number" prefix=" No. "/>
  ```
  Only styles with default locale `de-DE` sometimes use ` Nr. `.

Fixes #7222

2025-01-20 03:36 UTC, mdmower commented
@bwiernik - Would you be willing to review this?

2025-01-21 00:25 UTC, bwiernik commented
Thanks. The second fix should be `"N&ordm;"`

2025-01-21 00:31 UTC, bwiernik requested changes

2025-01-21 00:31 UTC, bwiernik commented on museum-national-dhistoire-naturelle.csl
> +      <text variable="number" prefix=" No. "/>
```suggestion
      <text variable="number" prefix="N&ordm;"/>
```

2025-01-21 00:41 UTC, mdmower commented
Thanks for the review and change suggestion @bwiernik . Looks like CI's report stage is failing for several PRs right now, but this is otherwise complete.

2025-01-21 01:04 UTC, bwiernik commented
Thanks! I'll merge once CI is fixed

2025-01-22 19:05 UTC, merged